// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysmonConfigPusher.Data;

#nullable disable

namespace SysmonConfigPusher.Data.Migrations
{
    [DbContext(typeof(SysmonDbContext))]
    [Migration("20251224160003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDeployment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("SysmonVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.ComputerGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComputerGroups");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.ComputerGroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "ComputerId");

                    b.HasIndex("ComputerId");

                    b.ToTable("ComputerGroupMembers");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.DeploymentJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.ToTable("DeploymentJobs");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.DeploymentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("JobId");

                    b.ToTable("DeploymentResults");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.NoiseAnalysisRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeRangeHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEvents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("NoiseAnalysisRuns");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.NoiseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupingKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NoiseScore")
                        .HasColumnType("REAL");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedExclusion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("NoiseResults");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.ComputerGroupMember", b =>
                {
                    b.HasOne("SysmonConfigPusher.Core.Models.Computer", "Computer")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SysmonConfigPusher.Core.Models.ComputerGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.DeploymentJob", b =>
                {
                    b.HasOne("SysmonConfigPusher.Core.Models.Config", "Config")
                        .WithMany("DeploymentJobs")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Config");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.DeploymentResult", b =>
                {
                    b.HasOne("SysmonConfigPusher.Core.Models.Computer", "Computer")
                        .WithMany("DeploymentResults")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SysmonConfigPusher.Core.Models.DeploymentJob", "Job")
                        .WithMany("Results")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.NoiseAnalysisRun", b =>
                {
                    b.HasOne("SysmonConfigPusher.Core.Models.Computer", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.NoiseResult", b =>
                {
                    b.HasOne("SysmonConfigPusher.Core.Models.NoiseAnalysisRun", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.Computer", b =>
                {
                    b.Navigation("DeploymentResults");

                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.ComputerGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.Config", b =>
                {
                    b.Navigation("DeploymentJobs");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.DeploymentJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("SysmonConfigPusher.Core.Models.NoiseAnalysisRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
